INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Adstringente');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agente anti-fúngico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agente anti-hiperlipidêmico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agente antiarrítmico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agente antimicrotubular');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agente antineoplásico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agente antineovascularizante');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agente antipsoriático');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agente biológico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agente de alcalinização');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agente de dissolução de cálculos biliares');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agente desbridante');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agente detoxificante');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agente diagnóstico radioativo');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agente diagnóstico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agente esclerosante');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agente esteroidal');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agente flebotônico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agente fotossensibilizante');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agente imunomodulador');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agente nootrópico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agente osmótico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agente quelante de ferro');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agente quelante');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agente remineralizador');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agente reversor do bloqueio neuromuscular');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agente sensibilizador de cálcio');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agente uterotônico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agentes antineovascularizantes');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agonista Adrenérgico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agonista adrenérgico não seletivo');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agonista alfa 1-adrenérgico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agonista alfa');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agonista alfa-2-adrenérgico.');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agonista alfa-adrenérgico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agonista beta-1-adrenérgico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agonista beta-2-adrenérgico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agonista beta-3-adrenérgico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agonista de dopaminainibidor de prolactina');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agonista do LHRH');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agonista do PPARγ');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agonista do receptor 5-HT1');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agonista do receptor GABAa');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agonista do receptor da prostaciclina');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agonista do receptor de trombopoetina');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agonista do receptor do GLP-1');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agonista do receptor nicotínico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agonista dopaminérgico não ergolínico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agonista dopaminérgico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agonista imidazolínico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agonista melatoninérgico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agonista parcial do receptor 5-HT1A');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agonista seletivo do receptor 5-HT4');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agonista seletivo para o receptor prostanoide FP');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Agonista α2');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Alcaloide da vinca');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Alimento');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Alquilante');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Alérgenos');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Aminoglicosídeo');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Aminoácido');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Analgésico do trato urinário');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Analgésico opioide');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Analgésico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Androgênico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anestésico geral inalatório');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anestésico geral');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anestésico local');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anestésico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anfenicol');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anfetamina');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anorexígeno');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Ansiolítico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antagonista benzodiazepínico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antagonista competitivo da ação da acetilcolina e dos agonistas muscarínicos');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antagonista de receptor de estrogênio');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antagonista de receptores H2');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antagonista do GnRH');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antagonista do PABA');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antagonista do hormônio liberador do hormônio luteinizante (LHRH)');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antagonista do receptor H2');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antagonista do receptor NMDA');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antagonista do receptor da angiotensina II');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antagonista do receptor de 5-HT');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antagonista do receptor de endotelina');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antagonista do receptor de ocitocina');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antagonista do receptor do hormônio do crescimento');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antagonista do receptore NMDA');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antagonista dos receptores de leucotrienos');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antagonista muscarínico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antagonista opioide');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antagonista seletivo competitivo do receptor da bradicinina do tipo 2 (B2)');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antagonista seletivo do receptor CXCR4 de quimiocinas');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antagonista seletivo do receptor de endotelina tipo A (ETA)');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antagonista seletivo dos receptores da substância P/neuroquinina (NK1) humana');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anti-helmíntico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anti-hemorroidal');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anti-hemorroidário');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anti-hemorrágico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anti-hiperglicemiante inibidor da DPP-4');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anti-hiperglicemiante');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anti-hipoglicemiante');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anti-histamínico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anti-homotóxico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anti-infeccioso');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anti-inflamatório não esteroidal');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anti-inflamatório');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antiacne');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antiagregante plaquetário');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antialcoólico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antialopecia');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antiandrogênico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antianginoso');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antianêmico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antiarrítmico classe V');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antiarrítmico de classe III');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antiarrítmico de classe IV');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antiartrósico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antiastênico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antibacteriano');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antibiótico antineoplásico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anticoagulante');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anticolinérgico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anticonvulsivante');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anticorpo biespecífico EGFR-MET');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anticorpo biespecífico ativador das células T');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anticorpo droga-conjugado (anti-CD30)');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anticorpo monoclonal (IgG1)');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anticorpo monoclonal (PD-L1)');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anticorpo monoclonal (anti-CD 38)');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anticorpo monoclonal (anti-CD20)');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anticorpo monoclonal (anti-CD52)');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anticorpo monoclonal (anti-CGRP)');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anticorpo monoclonal (anti-CGRPR)');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anticorpo monoclonal (anti-CTLA-4)');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anticorpo monoclonal (anti-FGF23)');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anticorpo monoclonal (anti-IL-17A)');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anticorpo monoclonal (anti-IL-23)');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anticorpo monoclonal (anti-IgE)');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anticorpo monoclonal (anti-PD-1)');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anticorpo monoclonal (anti-PD-L1)');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anticorpo monoclonal (anti-RANKL)');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anticorpo monoclonal (anti-SLAMF7)');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anticorpo monoclonal (anti-VEGF)');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anticorpo monoclonal IgG4 recombinante humano (inibidor da sinalização da IL-4)');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Anticorpo monoclonal');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antidepressivo antagonista do receptor de serotonina');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antidepressivo tricíclico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antidepressivo');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antidiarreico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antidiurético');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antiemético');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antiepiléptico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antiepilético');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antiespasmódico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antiespástico de ação medular');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antiestrôgenio');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antifibrinolítico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antifibrótico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antifisético');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antifolato');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antifúngico poliênico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antifúngico tópico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antifúngico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antiglaucomatoso');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antigonadotrópico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antigotoso');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antigripal');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antilipêmico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antimalárico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antimetabolitos');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antimetabólito');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antimicrobiano');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antineoplásico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antioxidante');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antiparasitário');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antiparatireoideano');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antiparatireoidiano');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antiparkinsoniano');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antiprotozoário');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antipruriginoso');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antipsicótico atípico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antipsicótico fenotiazínico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antipsicótico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antirretroviral');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antirreumático');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antisséptico ocular');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antisséptico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antitireoidiano');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antitrombótico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antitussígeno');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antitérmico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antiulceroso');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antivaricoso');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antivertiginoso');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antiviral inibidor da transcriptase reversa');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antiviral');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antiácido');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antraciclina');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antroposófico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antídoto da heparina');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antídoto dos antagonistas do ácido fólico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Antídoto');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Análago da vitamina D');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Análago de GLP-1');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Análago de insulina (ação gradual e longa)');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Análogo da prostaglandina E1');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Análogo da somatostatina');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Análogo da vitamina D');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Análogo de GLP-1');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Análogo de GLP-2');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Análogo de GnRH');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Análogo de insulina (ação longa)');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Análogo de insulina (ação rápida)');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Análogo de insulina (ação ultralonga)');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Análogo de nucleosídeo/nucleotídeo');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Análogo sintético da prostaciclina');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Análogo sintético da prostaglandina F2 (PGF2)');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Análogo sintético da vitamina D3');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Análogos');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Ativador natural da carbamoilfosfato sintase');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Bactericida');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Bacteriostático');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Barbitúrico potencializador GABA');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Benzodiazepínico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Beta-adrenérgico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Betabloqueador');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Betalactâmico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Biguanida');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Bisfosfonatos');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Bloqueador Neuromuscular');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Bloqueador alfa-1 adrenérgico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Bloqueador alfa-1-adrenérgico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Bloqueador alfa-2 adrenérgico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Bloqueador alfa-adrenérgico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Bloqueador da ativação dos receptores VEGF');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Bloqueador do canal de cálcio');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Bloqueador do canal de sódio');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Bloqueador do receptor de angiotensina II');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Bloqueador dos canais de potássio');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Bloqueador neuromuscular despolarizante');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Bloqueador neuromuscular não despolarizante');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Bloqueador neuromuscular');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Broncodilatador');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Carbapenêmico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Cefalosporina de 1ª geração');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Cefalosporina de 2ª geração');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Cefalosporina de 3ª geração');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Cefalosporina de 4ª geração');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Cefalosporina de 5ª geração');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Cefalosporina');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Cicatrizante oftálmico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Cicatrizante');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Cicloplégico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Coadjuvante no tratamento do climatério');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Cofator da hidroxilase para a fenilalanina');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Colagogo');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Colerético');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Colinérgico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Concentrado polieletrolítico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Contraceptivo');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Contraste radiológico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Contraste');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Corretor da CFTR');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Corticoide tópico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Corticoide');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Corticosteroide');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Depressor glutamatérgico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Derivado da Triazolopiridina');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Derivado imidazólico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Descongestionante nasal');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Descongestionante oftálmico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Descongestionante');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Desmelanizante');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Digestivo');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Diurético de alça');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Diurético inibidor da anidrase carbônica');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Diurético osmótico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Diurético poupador de potássio');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Diurético tiazídico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Diurético');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Drogas de ação lenta sintomáticas em osteoartrite');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Eletrólito');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Emoliente otológico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Emoliente');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Enzima digestiva');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Enzima');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Escabicida');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Esfoliante');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Estabilizador do humor');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Estabilizador seletivo de transtirretina');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Esteroide anabolizante');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Estimulador do sistema nervoso central');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Estimulante da guanilato ciclase solúvel');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Estimulante do apetite');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Estimulante do sistema nervoso central');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Estimulante respiratório');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Estimulante uterino');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Estimulante');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Estrógeno');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Expansor plasmático');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Expectorante');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'FSH - hormônio folículo estimulante altamente purificado');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Fator Estimulador de Colônias');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Fator de coagulação');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Fator de crescimento hematopoiético');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Fator de difusão enzimático');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Fibrinolítico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Fitoterápico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Flavonoide');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Fluidificante');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Gangliosídeo');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Glicilciclina');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Glicocorticoide');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Glicopeptídeo');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Glicosídeo cardíaco');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Hemoderivado');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Hemostático');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Hepatoprotetor');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Hidratante da mucosa nasal');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Hidratante');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Hipertensor');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Hipnótico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Hipolipemiante');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Hormônio antidiurético');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Hormônio da glândula pineal');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Hormônio de crescimento');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Hormônio folículo estimulante');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Hormônio gonadotrófico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Hormônio gonadotrópico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Hormônio luteinizante');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Hormônio paratireoidiano');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Hormônio tireoidiano');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Hormônio');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Imunoestimulante');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Imunoglobulina heteróloga');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Imunoglobulina humana');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Imunoglobulina');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Imunomodulador');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Imunoprotetor');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Imunossupressor seletivo');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Imunossupressor');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor Enzimático');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor adrenocortical');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor competitivo da 4-hidroxifenilpiruvato dioxigenase');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor da 5-alfa-redutase');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor da 5-fosfodiesterase');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor da ATP sintase');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor da DPP-4');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor da HMG-CoA redutase');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor da aromatase');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor da beta-lactamase');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor da biossíntese da parede celular');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor da bomba de prótons');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor da bomba de prótonsina');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor da bomba de prótonss');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor da coagulação');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor da colinesterase cerebral');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor da descarboxilase periférica');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor da enzima conversora da angiotensina (ECA)');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor da enzima conversora de angiotensina');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor da enzima fosfodiesterase-3 (PDE3)');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor da enzina conversora da angiotensina');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor da expressão de ICAM-1');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor da fosfodiesterase-4 (PDE4)');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor da glicosilceramida sintase');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor da janus quinase (JAK)');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor da monoaminoxidase');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor da proteína quinase');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor da reabsorção óssea');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor da recaptação da serotonina');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor da recaptação de serotonina e noradrenalina');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor da recaptação de serotonina');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor da ribonucleotídeo redutase');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor da síntese proteica');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor da tirosina quinase');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor da topoisomerase');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor da via Hedgehog');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor da α-glicosidase');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor da β-oxidação dos ácidos graxos');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor das enzimas poli (ADP-ribose) polimerase (PARP-1PARP-2 e PARP-3)');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor de Acetilcolinesterase');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor de C1 esterase');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor de CDK 4/6');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor de CDK4/6');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor de MEK 1 e 2');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor de MEK');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor de MEK1/2');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor de PARP');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor de esclerostina');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor de fosfatidilinositol 3-quinase');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor de histona desacetilase');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor de interleucina');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor de lipase');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor de microtúbulo DM1');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor de múltiplas quinases');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor de neprilisina');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor de protease de HIV-1.');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor de proteassoma');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor de proteinase alfa-1');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor de quinase serina-treonina BRAF');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor de renina');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor do DHT');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor do SGLT2');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor do hormônio de crescimento');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor do ácido δ-aminolevulínico sintetase');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor seletivo da colinesterase cerebral');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor seletivo da recaptação da norepinefrina e dopamina');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor seletivo de BTK');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor seletivo de pequena molécula da célula de linfoma B (Bcl-2)');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Inibidor seletivo do receptor de androgênico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Insulino-mimético');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Laxante');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Ligante de fosfato');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Lincosamida');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Lipopeptídeos cíclicos');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Lubrificante ocular');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Lubrificante');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Macrolídeo');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Medicamento homeopático');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Melanizante');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Midriático');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Mineral');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Modificador do splicing do pré-mRNA de sobrevivência do neurônio motor 2 (SMN2)');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Modulador seletivo do receptor estrogênico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Modulador serotoninérgico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Monobactâmico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Mucolítico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Neuroléptico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Neuropsicoestimulante');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Neurotônico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Nitrofurano');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Nutriente parenteral');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Nutrientes');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Oligonucleotídeo antisense');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Orexígeno');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Outros agentes modificadores de lipídios');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Outros fármacos que atuam no trato digestivo e metabolismo');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Outros fármacos usados em transtornos do sistema músculo-esquelético');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Outros medicamentos do sistema nervoso');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Outros medicamentos para o aparelho digestivo e metabolismo');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Oxazolidinona');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Pediculicida');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Penicilina');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Polimixina');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Polivitamínico do Complexo B');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Polivitamínico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Polivitamínicos com minerais');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Potencializador da CFTR');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Precursor da dopamina');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Probiótico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Procinético');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Progestágeno');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Prostaglandina E2');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Prostaglandina');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Proteína');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Quelante intracelular (cardioprotetor)');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Queratolítico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Queratoplástico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Quinolona');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Radiofármaco');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Redutor do nível do hormônio luteinizante');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Regulador da homeostase cálcica');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Regulador do metabolismo de cálcio e fosfato');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Relaxante muscular');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Removedor de cerume');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Repositor energético');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Repositor enzimático');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Repositor hidroeletrolítico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Resina permutadora de cálcio');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Retinoide');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Revulsivo');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Ribonucleotídeo pirimidínico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Rifamicina');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Rubefaciente');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Secativo');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Secretagogo de insulina');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Sedativo');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Solução irrigante');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Substituto do plasma');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Sulfonilureia');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Suplemento calórico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Suplemento dietético proteico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Suplemento eletrolítico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Suplemento mineral');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Suplemento vitamínico e mineral');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Suplemento vitamínico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Supressor da reabsorção óssea');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Surfactante pulmonar');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'TSH humano recombinante');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Taxano');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Terapias gênicas da retina');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Tetraciclina');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Trombolí­tico (ativador do plasminogênio)');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Tuberculostático');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Tônico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Urato-oxidase recombinante');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Vacina');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Varicoso');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Vasculoprotetor');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Vasoconstritor');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Vasodilatador cerebral');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Vasodilatador coronariano');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Vasodilatador periférico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Vasodilatador');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Vasopressor');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Venotônico');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Vitamina lipossolúvel');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Vitamina');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Vírus adeno-associado');
INSERT INTO `pebmedapps`.`tipo_metadado` (`tipo`, `valor`) VALUES ('CLASSE_MEDICAMENTO' , 'Ácidos graxos');
